INSERT INTO students (name,last_name,email,course_id) VALUES ('Juan', 'Perez','juan.perez@example.com',1);
INSERT INTO students (name,last_name,email,course_id) VALUES ('Maria', 'Santa Maria','maria.perez@example.com',2);
INSERT INTO students (name,last_name,email,course_id) VALUES ('Marcos', 'Aguirre','marcos.perez@example.com',1);
INSERT INTO students (name,last_name,email,course_id) VALUES ('Lucas', 'Zapallal','lucas.perez@example.com',3);
INSERT INTO students (name,last_name,email,course_id) VALUES ('Pedro', 'Espinoza','pedro.perez@example.com',2);
INSERT INTO students (name,last_name,email,course_id) VALUES ('Jaren', 'Palacios','jaren.perez@example.com',1);
INSERT INTO students (name,last_name,email,course_id) VALUES ('Devora', 'Rosa','devora.perez@example.com',3);
INSERT INTO students (name,last_name,email,course_id) VALUES ('Junior', 'Paredes','junior.perez@example.com',2);
INSERT INTO students (name,last_name,email,course_id) VALUES ('Frank', 'Espinal','frank.perez@example.com',3);
INSERT INTO students (name,last_name,email,course_id) VALUES ('Diego', 'Zambrano','diego.perez@example.com',2);
